services:
  registry:
    container_name: registry
    image: registry:3
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      docker-registry-net:
        aliases:
          - registry
      default: {}
    volumes:
      - ../registry-repo:/var/lib/registry
networks:
  docker-registry-net:
    name: docker-registry-net