services:
  jenkins:
    build: ../jenkins
    container_name: jenkins-ci
    ports:
      - "8080:8080"
    environment:
      DOCKER_HOST: tcp://dind:2375
      JENKINS_HOME_HOST: /var/jenkins_home
      TZ: Etc/GMT-3
    volumes:
      - ../jenkins_home:/var/jenkins_home
    networks:
      - default
      - docker-net
    restart: unless-stopped
    depends_on:
      - dind
  dind:
    image: "docker:29-dind"
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ''
      DOCKER_HOST: tcp://dind:2375
    entrypoint:
      - dockerd
      - --host=tcp://0.0.0.0:2375
      - --insecure-registry
      - registry:5000
    networks:
      docker-net:
        aliases:
          - dind
      docker-registry-net: {}
networks:
  docker-net: {}
  docker-registry-net:
    external: true